version: '3'
services:
  app:
    image: ruby:2.5.8
    working_dir: /app
    command: >
      bash -ec '
        gem install bundler -v 2.3.27
        gem update --system 3.2.3

        bundle install
        sleep infinity
      '
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db
    volumes:
      - .:/app:cached

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 3306
    ports:
      - '33306:3306'
