steps:
  - label: ':rspec: Rails {{matrix.rails}} (Ruby {{matrix.ruby}})'
    key: spec
    plugins:
      - docker-compose#v3.9.0:
          run: app
          env:
            - 'RAILS_VERSION={{matrix.rails}}'
            # used for names of JUnit XML files
            - BUILDKITE_JOB_ID
    timeout_in_minutes: 5
    command:
      - './docker-entrypoint.sh'
      - '.buildkite/test.sh'
    env:
      BYEBUG: '0'
      DEBUGGER: '0'
      RUBY_VERSION: '{{matrix.ruby}}'
    matrix:
      setup:
        rails:
          - '4.2'
          - '5.2'
        ruby:
          - '2.5.8'
          - '2.6.10'
      adjustments:
        - with:
            rails: '5.2'
            ruby: '2.5.8'
          skip: true
        - with:
            rails: '4.2'
            ruby: '2.6.10'
          skip: true
    artifact_paths:
      - log/*.log
      - tmp/rspec-junit-*.xml
      - tmp/rspec/*.txt
      - tmp/capybara/*
      - tmp/screenshots/*

  - wait: ~
    continue_on_failure: true

  - label: ':junit:'
    plugins:
      - junit-annotate#v1.9.0:
          artifacts: tmp/rspec-junit-*.xml
          job-uuid-file-pattern: rspec-junit-([^.]+)\.xml
          failure-format: file
